version: '3.8'

services:
  plex-newsletter-setup:
    build: ./app
    container_name: plex-newsletter-setup
    ports:
      - "5050:5050"
    volumes:
      - ./data:/data
    restart: unless-stopped
